name: Build and Publish Docker Image

on:
  push:
    branches:
      - docker-scan  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo $HOME
          pwd
          ls -lR
          docker build -t my-image:latest .

      - name: setup jfcli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog Platform url
          JF_URL: ${{ vars.JF_URL }} #

          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          # or
          # JFrog Platform access token added a group token.
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          jf rt ping

      - name: jf docker scan
        run: |
          jf docker scan my-image:latest

