name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

      - name: Log in to JFrog Artifactory Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
          registry: ${{ secrets.JFROG_REGISTRY }}

      - name: Tag Docker image
        run: |
          docker images
          docker tag my-image:latest kimt.jfrog.io/build-testing-local/testing:latest

      - name: Push Docker image to JFrog Artifactory
        run: |
          docker push kimt.jfrog.io/build-testing-local/testing:latest
